version: '3'
services:
  db:
    container_name: issues_db
    image: postgres:14.6
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: issues_app
      POSTGRES_PASSWORD: issues_app
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  web: &web
    container_name: issues_web
    build: .
    command: bash -c "service cron start && bundle exec whenever --update-crontab && rm -rf tmp/pids/server.pid && rails db:create db:migrate && rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      ISSUES_APP_DATABASE_PASSWORD: issues_app
      WEBPACKER_DEV_SERVER_HOST: webpacker
      MINIO_ROOT_USER: issues_app
      MINIO_ROOT_PASSWORD: issues_app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db
      - minio
    tty: true
    stdin_open: true
  webpacker:
    <<: *web
    container_name: issues_webpacker
    depends_on:
      - web
      - minio
    command: bash -c "./bin/webpack-dev-server"
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 3035:3035
  minio:
    container_name: issues_minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: issues_app
      MINIO_ROOT_PASSWORD: issues_app
    entrypoint: bash
    command: -c "/opt/bin/minio server /data --console-address :9001"
    volumes:
      - minio_volume:/data
    ports:
      - 9000:9000
      - 9001:9001
  mc:
    container_name: mc
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc config host rm local;
        /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 issues_app issues_app;
        /usr/bin/mc mb --quiet local/issues-app-development;
        /usr/bin/mc policy set public local/issues-app-development;
        /usr/bin/mc mb --quiet local/issues-app-test;
        /usr/bin/mc policy set public local/issues-app-test;
      "
volumes:
  db_volume:
    driver: local
  minio_volume:
    driver: local
