AWSTemplateFormatVersion: 2010-09-09

Parameters:
  SSHKey:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
  allowedIP:
    Description: IP address allowed to access EC2
    Type: String

Resources:
  # VPC
  issuesLiveVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.2.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: issues-live-vpc

  # InternetGateway
  issuesLiveIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: issues-live-igw

  issuesLiveAttachGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref issuesLiveIGW
      VpcId: !Ref issuesLiveVPC

  # Subnet
  issuesLivePublic1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.2.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: issues-live-public1a
      VpcId: !Ref issuesLiveVPC
  issuesLivePrivate1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.2.2.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: issues-live-private1a
      VpcId: !Ref issuesLiveVPC

  # Route Table
  issuesLivePublic1aRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Name
          Value: issues-live-vpc-rt
      VpcId: !Ref issuesLiveVPC

  issuesLiveRTAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref issuesLivePublic1aRouteTable
      SubnetId: !Ref issuesLivePublic1a

  issuesLiveRouteIGW:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref issuesLiveIGW
      RouteTableId: !Ref issuesLivePublic1aRouteTable

  # EC2
  issuesLiveEC2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-northeast-1a
      ImageId: ami-0bba69335379e17f8
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref issuesLivePublic1a
          GroupSet:
            - !Ref issuesLiveEC2SG
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo timedatectl set-timezone Asia/Tokyo
          sudo localectl set-locale LANG=ja_JP.utf8
          source /etc/locale.conf
          sudo systemctl restart crond.service
          sudo amazon-linux-extras install -y nginx1
          sudo systemctl start nginx
          sudo yum install -y git
          sudo yum install -y gcc-c++ openssl-devel readline-devel zlib-devel
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install v16.16.0
          npm install --global yarn
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          source ~/.bashrc
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          sudo ~/.rbenv/plugins/ruby-build/install.sh
          rbenv install 3.0.1
          rbenv global 3.0.1
      Tags:
        - Key: Name
          Value: issues-live-ec2

  # EC2 Security Group
  issuesLiveEC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: issues-live-ec2-sg
      GroupDescription: HTTP and SSH
      VpcId: !Ref issuesLiveVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref allowedIP
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref allowedIP
